Fixes for git xet migrate 502 transport error. (#363)
This PR adds a fix for the 502 transport error for when it seems pushing
all the branches gets
```
error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500
send-pack: unexpected disconnect while reading sideband packet
fatal: the remote end hung up unexpectedly
```
This fixes one possible cause, but then as backup pushes each branch
individually.

---------

Co-authored-by: Hoyt Koepke <hoytak@xethub.com>